server:
    port: 8123
spring:
  datasource:
    url: "jdbc:mysql://82.73.212.90:3307/dpm"
    username: "2nowabout"
    password: "SecurePassword1!"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka