name: Docker CI

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Set up JDK    
      uses: actions/setup-java@v1      
      with:        
        java-version: 1.11
    - name: Build with Maven      
      run: mvn package
    - name: Docker build
      run: docker build . --tag registry.vimuens.nl/user-api:latest
    - name: Publish to Docker Registry
      run: docker push registry.vimuens.nl/user-api:latest
      
